### ISSUE TITLE
How can I set the plate in my home country.

### ISSUE THREAD

**Issue by mertbuldur** [RobertSasak/react-native-openalpr#100]
Hello, I am using this package in my react native project. Thank you very much to those who prepared the package.
How do I make plate settings for Turkey?

**Comment by RobertSasak** [comment]
This library is just a wrapper for a OpenALPR. It will use _openalpr.conf_ file. You need to search online for a _openalpr.conf_ file for Turkey. This might be a good start. 
https://discuss.openalpr.com/t/turkey-tr-plate-number-recognize/590

Once you get _openalpr.conf_ for Turkey you simply swap it with the one provided in the wrapper. Remember to post your findings to this issue to help others.

**Comment by mertbuldur** [comment]
![Ekran Resmi 2020-09-30 13 21 32](https://user-images.githubusercontent.com/8089725/94673742-dce81980-031f-11eb-80a8-03a87a79085c.png)
Thanks for comment.Where is openalpr.conf folder ?  I dont find this :/ sorry

**Comment by RobertSasak** [comment]
Good point. Config files are actually located in 
https://github.com/RobertSasak/react-native-openalpr/tree/master/ios/Frameworks/openalpr.framework/runtime_data/config
You can specify which config file to load by country prop.

**Comment by mertbuldur** [comment]
@RobertSasak  so thank you :D
