### ISSUE TITLE
iPhone zoom and native multi camera support

### ISSUE THREAD

**Issue by richiepreece** [RobertSasak/react-native-openalpr#103]
@RobertSasak I'm new to this repo, but I'd love to get it modernized since it appears as though a lot of work was done 10 months ago or more.

I'm looking to get support for multi cameras in iphone so I don't need to rely on the wider-angle lens, but can use a telephoto to scan from a further distance. I'm happy to take this task on, if you wouldn't mind pointing me in the general direction of how to accomplish this.

Is there something that would give me this ability already? I don't see anything listed in the docs except that zoom is for Android-only.

**Comment by RobertSasak** [comment]
I am glad to hear your interest. I am just a maintainer for this repository, so I do not know as much. 

It looks like you can select camera at this line. https://github.com/RobertSasak/react-native-openalpr/blob/master/ios/ALPRCameraManager.mm#L364

You can try to experiment with it by providing front camera and perhaps also tele camera if available. You can post your findings here, but I am also available at gitter for a chat.
