### ISSUE TITLE
null is not an object (evaluating 'ALPRCameramanager.Aspect')

### ISSUE THREAD

**Issue by websky112** [RobertSasak/react-native-openalpr#104]
![image](https://user-images.githubusercontent.com/50550531/103522548-64698b00-4e2f-11eb-88e0-2d6ed8785d3b.png)
I have tried to use this package on Expo project, and got the above issue.
How can I fix this issue?

**Comment by RobertSasak** [comment]
Expo is supporting on selected native modules. That is the whole point of Expo. _react-native-openalpr_ is not supported by Expo. You need to **eject** from expo in order to use this library.

**Comment by pke** [comment]
This also happens with current RN 0.70.0 non-expo projects too. Any idea how to fix it?

**Comment by RobertSasak** [comment]
Library is not installed properly.

**Comment by pke** [comment]
Installed via yarn according to the instructions.

**Comment by RobertSasak** [comment]
Try to reprodiuce the issue in example folder.
