### ISSUE TITLE
Doesit support UAE vehicle plate number?

### ISSUE THREAD

**Issue by shivaraj12345** [RobertSasak/react-native-openalpr#108]
I want to fetch detail of UAE vehicle plate numbers which includes arabic langauge ...can someone please let me know if this library supports Arabic text

**Comment by RobertSasak** [comment]
This library is just a wrapper around OpenALPR. Any licence plate that is supported by OpenALPR is also supported by this wrapper. That being said, you need a config file for UAE licence plates.
