### ISSUE TITLE
_reactNativeOpenalpr.takePicture in android on press of take picture?

### ISSUE THREAD

**Issue by shivaraj12345** [RobertSasak/react-native-openalpr#109]
Hi , I am able to run the build but onpress of take picture button i am geeting below error

Possible Unhandled Promise Rejection (id: 2):
TypeError: (0, _reactNativeOpenalpr.takePicture) is not a function. (In '(0, _reactNativeOpenalpr.takePicture)({
                  width: 4032,
                  height: 3024,
                  quality: 0.8
                })', '(0, _reactNativeOpenalpr.takePicture)' is undefined)

**Comment by RobertSasak** [comment]
What platform do you get this error? Taking pictures is only available on iOS.

**Comment by shivaraj12345** [comment]
What would be the solution for android?

**Comment by RobertSasak** [comment]
Contribute with a PR.

**Comment by shivaraj12345** [comment]
Hi please can u tell me how can i work out without takepicture method, i want to read plate number in android

**Comment by RobertSasak** [comment]
Clone this repo and open example project. Run it in Android Studio and test it on you phone.
