### ISSUE TITLE
Apple Mach-O Linker (id) Error

### ISSUE THREAD

**Issue by llanginger** [RobertSasak/react-native-openalpr#13]
### Lib specs:

react: 16.0.0-alpha.6
react-native: 0.44.2
react-native-openalpr: 1.0.6

### Issue:

Hi there,

I'm sure that I'm missing something fairly obvious but I have tried 4 or 5 times now from scratch to get your library into my project and I consistently get the same error:

![screen shot 2017-08-24 at 5 04 13 pm](https://user-images.githubusercontent.com/16844415/29694546-e211f8d2-88f1-11e7-9f58-0c30ccc20135.png)

I can successfully build and run the project in /Example and I have tried replicating everything I can think of from its setup but nothing so far has worked. I HAVE noticed a few differences that I do not know how to resolve (or if they're significant). On the left you will see the example project (that builds and runs) and on the right you will see the equivalent screen/section in my project where I see differences:

### Screen Shots

![screen shot 2017-08-24 at 4 49 30 pm](https://user-images.githubusercontent.com/16844415/29694584-37031ee8-88f2-11e7-8794-171244f82c59.png)

In the above SS, there is a folder in the Frameworks library called AssetsLibrary that does not appear in the instructions. Also the individual frameworks appear red, very peculiar.

![screen shot 2017-08-24 at 4 50 20 pm](https://user-images.githubusercontent.com/16844415/29694619-835f4b7c-88f2-11e7-82ab-2ef953ad1e11.png)

Once again in the Build Phases the references to the frameworks are visually very different and I'm not sure why this is or if it matters.

### Guess:

When I import the frameworks from `node_modules/react-native-openalpr/ios/Frameworks`, nothing gets added to my Framework Search Paths. This strikes me as meaningful, especially with the above-mentioned visual differences I'm seeing. 

Any help would be greatly appreciated!

**Comment by VvanGemert** [comment]
Hi llanginger,

I've had the same problem with compiling. I solved it by adding the following libraries:

- CoreVideo.framework,
- AssetsLibrary.framework
- CoreMedia.framework 

in 'Link with Libraries'.

I found the solution here:

https://stackoverflow.com/questions/23634940/opencv2-framework-not-compile-with-linker-flag-objc

**Comment by Dreyer** [comment]
@VvanGemert this should really be added to the setup instructions because otherwise it doesn't compile

**Comment by jqn** [comment]
For me I ran into three different errors running this library. One I had to add:
- $(PROJECT_DIR)/../node_modules/react-native-openalpr/ios/Frameworks to frameworks search path
- Add
  -CoreVideo.framework,
   -AssetsLibrary.framework
   -CoreMedia.framework
And finally update proptypes in the index.js file of this library

**Comment by smancebo** [comment]
Hi
go to [this link](https://docs.opencv.org/2.4/doc/tutorials/ios/video_processing/video_processing.html#adding-the-camera) and add all the frameworks listed here and add $(PROJECT_DIR)/../node_modules/react-native-openalpr/ios/Frameworks 
to the Framwork Search path (in debug and release)

works for me

**Comment by RobertSasak** [comment]
Seems to be resolved. Closing for now.
