### ISSUE TITLE
Configuration with name 'compile' not found.

### ISSUE THREAD

**Issue by sidroker** [RobertSasak/react-native-openalpr#132]
Hello,

I am trying to implement this module in my and i face below issue,

On android side
-Caused by: org.gradle.api.plugins.UnknownPluginException: Plugin with id 'maven' not found.
after resolving it will got another error like 
Build file '/Users/metizsoft_m1/NumberScanDemo/node_modules/react-native-openalpr/android/build.gradle' line: 106

A problem occurred configuring project ':react-native-openalpr'.
> Configuration with name 'compile' not found.

On Ios Side got below Error

Showing All Issues
File not found: /usr/lib/libstdc++.6.0.9.dylib
![Screenshot 2022-04-06 at 5 02 50 PM](https://user-images.githubusercontent.com/103116034/161965504-cfbc140d-f6f8-424c-88a9-9be89ad20352.png)
![Screenshot 2022-04-06 at 5 03 05 PM](https://user-images.githubusercontent.com/103116034/161965531-c2296b68-82e5-43c0-90c6-0e602dea5227.png)

**Comment by RobertSasak** [comment]
iOS issue is described here https://github.com/RobertSasak/react-native-openalpr/issues/105#issuecomment-831113831
