### ISSUE TITLE
Quick Recognition

### ISSUE THREAD

**Issue by Ollie-NTP** [RobertSasak/react-native-openalpr#14]
Hello,
I installed openalpr on both versions, iOS is running very well but on Android I have a very high lag (I use a Samsung S7), delayed reading ... is there any config for this? A screenshot if the number is the one I'm looking for how can I do? I saw that the camera module is not really the camera... Thank you,  I am 
waiting for your answer

**Comment by Progoogler** [comment]
The only configs that I'm aware of are the props which are passed to `<ALPRCamera .../>`. I've noticed that when I lower the `captureQuality` prop, the response time of `onPlateRecognized`is quicker. My tests show a response time of 1 second for low and 3+ seconds for medium or high quality. I'm using a Samsung S6 Edge+.

**Comment by Bobozee** [comment]
I have experienced the same issue, on iOS it works just perfect but on Android it lags and sometimes I even do not get any plate recognized. The camera is set on medium quality.

**Comment by RobertSasak** [comment]
From my experience it helps to try different camera settings. Medium seems to work best. However there is no way to choose best setting for all Android devices. As there is no much to do, I am closing this issue.
