### ISSUE TITLE
Crash on android emulator

### ISSUE THREAD

**Issue by arnsa** [RobertSasak/react-native-openalpr#15]
Hello,

I've been trying to make this library work on Android. It seems to be working fine on the real device, but when I am trying to launch it from android emulator, whenever I open up the camera, it crashes after 1-2 seconds. I've linked everything using instructions. I've also added camera permissions. Copy-pasted code from the README. Does anyone have any clue what could be wrong here?

**Comment by RobertSasak** [comment]
Closing in favour of https://github.com/RobertSasak/react-native-openalpr/releases/tag/v2.0.1
