### ISSUE TITLE
Photo Capture 

### ISSUE THREAD

**Issue by Ollie-NTP** [RobertSasak/react-native-openalpr#18]
i have a new issue, i want to make a capture screen in the same moment when onPlateRecognizer() return a plate number, a different image beside off the image for recogoneze plate for save this in phone memory ( i need this for android and ios ) please, help me ! :)

**Comment by Progoogler** [comment]
You're in luck. I just recently submitted a PR for including an image `capture()` feature in the Android version. If you clone the `openalpr-with-image-capture` branch of this repo, you should have access to the capture functionality which you are seeking. You would be able to do something like this with your `onPlateRecognized()`:

```
  onPlateRecognized({ plate, confidence }) {
    if (confidence > 0.9) {
      if (this.license !== plate) { // Only take a picture if the plate recognized is different from the recent one
         this.license = plate;
         this.takePicture();
       }
    }
  }
}

takePicture() {
  this.cameraRef.capture()
  .then(() => ....)
  .catch((e) => ...)
}
```

I will look into adding this feature into iOS when the time comes. In the meantime, you're welcome to get started on a new branch! Just refer to react-native-camera and you'll be tip top!

**Comment by franck-nadeau** [comment]
I added that functionality for iOS in this [PR](https://github.com/RobertSasak/react-native-openalpr/pull/49)

Here is how to use it:

````
this. cameraRef.takePicture().then(
        uri => {
              console.log(`uri for the image ${uri}`;
        },
        error => {
              console.log(`Error : ${error}`;
        }
      );
````

**Comment by cdvntr** [comment]
Hey @Friendly-Robot,

I can't install the branch via package.json

"react-native-openalpr": "git+http://git@github.com/RobertSasak/react-native-openalpr.git#openalpr-with-image-capture"

Also tried master, do you have a clue?

**Comment by franck-nadeau** [comment]
Hello,

You will need to use it as follows:

"react-native-openalpr": "RobertSasak/react-native-openalpr#master",

Cheers,

Francois

On Apr 30, 2019, at 8:51 AM, Codeventure <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @Friendly-Robot<https://github.com/Friendly-Robot>,

I can't install the branch via package.json

"react-native-openalpr": "git+http://git@github.com/RobertSasak/react-native-openalpr.git#openalpr-with-image-capture"

Also tried master, do you have a clue?

**Comment by cdvntr** [comment]
Hi @franck-nadeau,

I get CameraManager.takePicture is not a function error and when i log the ref i actually can't see the function.

**Comment by franck-nadeau** [comment]
Hello.

A few things, 
- first you need to be on master because there hasn't been a release for about 2 years.
````
 "react-native-openalpr": "RobertSasak/react-native-openalpr#master",
````
- second, this will only work on iOS. 
- third you should use the [Camera.takePicture()](https://github.com/RobertSasak/react-native-openalpr/blob/b7c9ea468c2669ee4d54fd7fbf136d06482ff627/index.js#L103) helper function that I added. 

Let me know if this still does not work for you.

**Comment by cdvntr** [comment]
@franck-nadeau Thanks for the quick answer,

- This is on my package.json : "react-native-openalpr": "RobertSasak/react-native-openalpr#master",
- I am working on ios.

After calling the function from the module not the ref, i get;

`TypeError: _reactNativeOpenalpr.default.takePicture is not a function`.

**Comment by franck-nadeau** [comment]
I am not sure why that is. It is working fine off my own branch. That is, you could use the following:

````
"react-native-openalpr": "franck-nadeau/react-native-openalpr#master",
````

Here is my code for your info.

````
  onPlateRecognized({ plate, confidence }) {
    if (confidence > 90) {
      // We got a good match, lets take a screenshot of it.
      this.refs.camera.takePicture().then(
        uri => {
        },
        error => {
        }
      );
    }
  }

render() {
...
 <Camera
          ref="camera"
....
````

**Comment by RobertSasak** [comment]
I released master as 1.2.0 https://github.com/RobertSasak/react-native-openalpr/releases/tag/1.2.0
It contains also Take picture ios PR https://github.com/RobertSasak/react-native-openalpr/pull/49

**Comment by CevaComic** [comment]
Can someone update the example in the repo with this method too ? I can't manage to make it work , i would appreciate a working example. Thank you

**Comment by RobertSasak** [comment]
I have updated the example https://github.com/RobertSasak/react-native-openalpr/blob/master/example/App.js
