### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by RobertSasak** [RobertSasak/react-native-openalpr#20]
I understand that higher resolution images will not necessary improve the licence plate recognition. More over it would use more CPU.

Instead of resizing image down to 480x360 I would like to crop the center of the image to size 480x360 (Camera.constants.CaptureQuality.medium). User of the app will be instructed to point camera in such a way that a licence plate is in the center of the image. 

This would allowed to recognise licence plate from much longer distance.

**Comment by nirvaat** [comment]
Yes I was also feeling lack of zoom feature. If we can set the zoom level of the camera with same aspect ratio, then it will be easier to read number plates from a distance. Nowadays the camera's has great resolution, so zooming will not distort the image, it can be digital zoom.

**Comment by RichardPiel** [comment]
Do you know if it is possible to easily add a digital zoom feature?

**Comment by RobertSasak** [comment]
You may need to implement zoom here. PR is more than welcome. 
https://github.com/RobertSasak/react-native-openalpr/blob/master/ios/ALPRCamera.m#L187

**Comment by RichardPiel** [comment]
Okay, thanks. I'll try. I'll get back to you as soon as I can.

**Comment by RichardPiel** [comment]
I've just developed the zoom support for Android, how to make a pull request? I don't have the rights to create a branch and send modifications.
