### ISSUE TITLE
country br does not work

### ISSUE THREAD

**Issue by betiol** [RobertSasak/react-native-openalpr#23]

**Comment by andrefilipin** [comment]
Same here, doesn't work

**Comment by dodds-cc** [comment]
Looking at the openalpr.conf file, it only seems to support us and eu at the moment. I was trying with GB plates for ages!

**Comment by dodds-cc** [comment]
try looking here: for the conf files: https://github.com/openalpr/openalpr/tree/master/runtime_data/config
