### ISSUE TITLE
Slow first load

### ISSUE THREAD

**Issue by RobertSasak** [RobertSasak/react-native-openalpr#26]
It takes around 8s before *<Camera>* component show for the first time on iOS. UI thread is frozen and after 8 seconds camera show on the screen. Any following showing/hiding camera is very fast.
Has anybody else similar issue?

**Comment by RassaLibre** [comment]
I am having the same issue. I just show a spinner underneath...

**Comment by RobertSasak** [comment]
Me too. I also show a spinner for now. I look into the code but I could not figure out what is taking so long.

**Comment by bcalik** [comment]
Does anyone have a solution please?

**Comment by mike-at-tiffik** [comment]
I managed to get around this forcing '[self.session startRunning]' to run in the main queue. This can be found in the startSession method in the ALPRCameraManager.mm file. As this seems like a threading issue use at your own discretion.

<img width="1084" alt="screen shot 2018-09-21 at 13 28 32" src="https://user-images.githubusercontent.com/42147232/45881167-500a3d00-bda2-11e8-9f8e-7216ba02d8da.png">

**Comment by RobertSasak** [comment]
Nice. Well done @mike-at-tiffik . Since it is just three lines of code, can you please submit a PR?

**Comment by mike-at-tiffik** [comment]
Will do. 

Cheers

Mike





Mike Boyns
Software Developer

email: 	mike@tiffik.com
web:	 http://www.tiffik.com
mobile:	07743 719932 

---
Tiffik Solutions Limited 

Specialising In Creating And Delivering Bespoke IT Solutions.

Website design, E-Commerce and Mobile


Registered in England and Wales. No 11398486
---
