### ISSUE TITLE
error in iOS

### ISSUE THREAD

**Issue by valinaga** [RobertSasak/react-native-openalpr#28]
I follow the instructions as per the install documentation but I got an errror:
```
ld: framework not found openalpr
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
It looks like after adding the frameworks to the project there were no updates on framework search path. But if I try to manually add the path 
```
$(PROJECT_DIR)/../node_modules/react-native-openalpr/ios/Frameworks
```
I got the error:
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_ALAssetsLibrary", referenced from:
      objc-class-ref in opencv2(cap_ios_video_camera.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Any idea? I'm on XCode 9.2

**Comment by RobertSasak** [comment]
Your post feel familiar, but I cannot recall details. I made few notes that I hope will help you. 
1. Note
Ensure that "This should cause the project to add a framework search path to the project's build settings (e.g. $(PROJECT_DIR)/../node_modules/react-native-openalpr/ios/Frameworks)."

2. Note
Problem with: objc-class-ref in opencv2(cap_ios_video_camera.o)
Follow instructions from https://github.com/cardash/react-native-openalpr/issues/7 and add Assets library

**Comment by jqn** [comment]
Take a look at this issue it might be what you are running into https://github.com/cardash/react-native-openalpr/issues/13

**Comment by esbasti** [comment]
I fixed the error by adding 3 more libraries to the project, including AssesLibrary.framework

https://stackoverflow.com/questions/23634940/opencv2-framework-not-compile-with-linker-flag-objc

**Comment by jsastriques** [comment]
ld: framework not found openalpr
clang: error: linker command failed with exit code 1 (use -v to see invocation)

i get this error, please some help

**Comment by franck-nadeau** [comment]
openalpr  is outside your project directory, so you need to add the following: 

````
$(PROJECT_DIR)/../node_modules/react-native-openalpr/ios/Frameworks/
````

To your project's ````Framework Search Path````

**Comment by RobertSasak** [comment]
As this is an old issue I am closing it now. Feel free to open new one.

**Comment by arthur5005** [comment]
> I fixed the error by adding 3 more libraries to the project, including AssesLibrary.framework
> 
> https://stackoverflow.com/questions/23634940/opencv2-framework-not-compile-with-linker-flag-objc

That fixed it for me!
