### ISSUE TITLE
Image is flipped and upside down

### ISSUE THREAD

**Issue by CptFabulouso** [RobertSasak/react-native-openalpr#36]
Running the example on device Nexus 5x, Android 8.1.0

For some reason the image is flipped both horizontally and vertically, so upper left corner in real word is in bottom right corner. Plate numbers are read as camera sees them. Switching orientation only rotates the menu.

Works alright on nexus 4, Android 5.1.1

**Comment by RobertSasak** [comment]
Can you verify that issue still exists on last release?

**Comment by CptFabulouso** [comment]
Yes, the issue still exists

**Comment by CptFabulouso** [comment]
I found this [post on reddit](https://www.reddit.com/r/Android/comments/3rjbo8/nexus5x_marshmallow_camera_problem/cwqzqgh?utm_source=share&utm_medium=web2x), that might be useful.
