### ISSUE TITLE
Example App does not work on Android, shows undefined is not an object

### ISSUE THREAD

**Issue by cvl01** [RobertSasak/react-native-openalpr#40]
![screenshot_20180929-143520](https://user-images.githubusercontent.com/30371838/46245846-3ea1e000-c3f5-11e8-83c7-70b094aae0e4.png)

What can I do to solve this error on android?

**Comment by KnapSac** [comment]
#https://github.com/react-native-community/react-native-camera/issues/1005#issuecomment-347780455

@hawkup 's answer fixed it for me, just change the following code in camera.js:
```js
// components/camera.js
import React, { Component, PropTypes } from 'react';

//to

import React, { Component } from 'react';
import PropTypes from 'prop-types';

**Comment by FrenchBully** [comment]
This is also happening on IOS, even with the updated Camera.js file. Any other ideas @KnapSac?

**Comment by FrenchBully** [comment]
@RobertSasak yes, CameraManager is undefined. I'll try reinstalling to be sure I didn't miss a step. Thanks for the reply.
