### ISSUE TITLE
 I downloaded the example but when I run the project shows this error

### ISSUE THREAD

**Issue by joaodematejr** [RobertSasak/react-native-openalpr#41]
undefined is not an object (evaluating '_react.PropTypes.oneOfType')
<unknown>
    camera.js:46:26
loadModuleImplementation
    require.js:320:6
guardedLoadModule
    require.js:214:36
metroRequire
    require.js:136:24
<unknown>
    consultasCamera.js:12
loadModuleImplementation
    require.js:320:6
guardedLoadModule
    require.js:214:36
metroRequire
    require.js:136:24
<unknown>
    App.js:8
loadModuleImplementation
    require.js:320:6
guardedLoadModule
    require.js:214:36
metroRequire
    require.js:136:24
<unknown>
    index.js:4
loadModuleImplementation
    require.js:320:6
guardedLoadModule
    require.js:207:45
metroRequire
    require.js:136:24
global code
    

    static propTypes = {
        ...View.propTypes,
        aspect: PropTypes.oneOfType([
            PropTypes.string,
            PropTypes.number
        ]),
        captureQuality: PropTypes.oneOfType([
            PropTypes.string,
            PropTypes.number
        ]),
        country: PropTypes.string,
        onPlateRecognized: PropTypes.func,
        plateOutlineColor: PropTypes.string,
        showPlateOutline: PropTypes.bool,
        rotateMode: PropTypes.oneOfType([
            PropTypes.string,
            PropTypes.number
        ]),
        torchMode: PropTypes.oneOfType([
            PropTypes.string,
            PropTypes.number
        ]),
        touchToFocus: PropTypes.bool,
    };

**Comment by RobertSasak** [comment]
https://github.com/cardash/react-native-openalpr/pull/24

PropTypes are not part of react any more. There is already a pull request for it. In a meanwhile simply rewrite imports of PropTypes in camera.js

**Comment by joaodematejr** [comment]
Get resolved by importing inside the file import PropTypes from 'prop-types'; camera.js
