### ISSUE TITLE
Update to work with latest react version

### ISSUE THREAD

**Issue by kabus202** [RobertSasak/react-native-openalpr#44]
Is it possible to update the this project to work with the latest project:

this is the error i get on a blank react template 

_> Configure project :openalpr 
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (25.0.0) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.4.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '25.0.0'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':opencv'.
> Could not resolve all files for configuration ':opencv:classpath'.
   > Could not find com.android.tools:common:25.3.2.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/common/25.3.2/common-25.3.2.pom
         https://jcenter.bintray.com/com/android/tools/common/25.3.2/common-25.3.2.jar
     Required by:
         project :opencv > com.android.tools.build:gradle:2.3.2 > com.android.tools.build:gradle-core:2.3.2 > com.android.tools.build:builder:2.3.2
         project :opencv > com.android.tools.build:gradle:2.3.2 > com.android.tools.build:gradle-core:2.3.2 > com.android.tools.build:builder:2.3.2 > com.android.tools.build:manifest-merger:25.3.2
         project :opencv > com.android.tools.build:gradle:2.3.2 > com.android.tools.build:gradle-core:2.3.2 > com.android.tools.build:builder:2.3.2 > com.android.tools.ddms:ddmlib:25.3.2
         project :opencv > com.android.tools.build:gradle:2.3.2 > com.android.tools.build:gradle-core:2.3.2 > com.android.tools.build:builder:2.3.2 > com.android.tools.analytics-library:shared:25.3.2
         project :opencv > com.android.tools.build:gradle:2.3.2 > com.android.tools.build:gradle-core:2.3.2 > com.android.tools.build:builder:2.3.2 > com.android.tools.analytics-library:tracker:25.3.2
         project :opencv > com.android.tools.build:gradle:2.3.2 > com.android.tools.build:gradle-core:2.3.2 > com.android.tools.build:builder:2.3.2 > com.android.tools:sdklib:25.3.2 > com.android.tools.layoutlib:layoutlib-api:25.3.2
         project :opencv > com.android.tools.build:gradle:2.3.2 > com.android.tools.build:gradle-core:2.3.2 > com.android.tools.build:builder:2.3.2 > com.android.tools:sdklib:25.3.2 > com.android.tools:dvlib:25.3.2
         project :opencv > com.android.tools.build:gradle:2.3.2 > com.android.tools.build:gradle-core:2.3.2 > com.android.tools.build:builder:2.3.2 > com.android.tools:sdklib:25.3.2 > com.android.tools:repository:25.3.2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org_

**Comment by phithu** [comment]
me too

**Comment by Aiiros** [comment]
any updates ?

**Comment by RobertSasak** [comment]
Work in progress. iOS is ready and support react 0.60. Changes are in separate branch for now, but I will merge it soon. However Android is missing 64 bit libraries.

**Comment by RobertSasak** [comment]
Closing in favour of https://github.com/RobertSasak/react-native-openalpr/releases/tag/v2.0.1
