### ISSUE TITLE
Balck screen when unmount camera

### ISSUE THREAD

**Issue by AguGriguol** [RobertSasak/react-native-openalpr#45]
hello!

I have a problem with this library! 

When render Camera I don't have problem but when change of state "camera_open" to false, the screen turns black. If I minimize the app and I resume the app, the app recover the state with the image "Welcome".

```
if(this.state.camera_open){
            return (
                <View style={{flex: 1}}>
                    <View style={{position: 'absolute', backgroundColor: 'transparent'}}>
                        <Image source={camera} style={{margin:0.5}}/>
                    </View>
                    <Camera
                        ref='camera'
                        style={{flex: 1}}
                        aspect={Camera.constants.Aspect.fill}
                        captureQuality={Camera.constants.CaptureQuality.midium}
                        country="us"
                        onPlateRecognized={({ plate, confidence }) => this._onPlateRecognized(plate, confidence)}
                        torchMode={Camera.constants.TorchMode.off}
                        touchToFocus={true}
                        showPlateOutline={false}
                        />
                </View>
            );
} else {
   return (
          <View style={{flex: 1}}>
              <Text source={Welcome} style={{margin:0.5}}></Text>
           </View>
    );
}
```

**Comment by arthur5005** [comment]
Noticing something similar on iOS. Crashes about 10% of the time when unmounting the Camera. Thought maybe it was the `onPlateRecognized` event hitting the component after it's been unmounted. 

Guarding didn't seem to do anything.

I'll have some more time to look into what logs say. Otherwise, this package works great, scans are insanely fast.

**Comment by arthur5005** [comment]
Well, I got around the issue for now by using react-navigation and putting the camera on a parent route that never unmounts.

**Comment by RobertSasak** [comment]
Closing for now
