### ISSUE TITLE
Black / blank screen when loading camera

### ISSUE THREAD

**Issue by inetdigital** [RobertSasak/react-native-openalpr#46]
Trying to implement the project on IOS, the application builds and launches fine both in the simulator and a real device, but after accepting the access to camera prompt the application hangs on a black screen, the camera never opens. There is no build or runtime errors output in Xcode, the only warning output is;

```ALPRCameraManager requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of```

Environment:

MacOS 10.14
Xcode 10
IOS 12

react: 16.6.3
react-native 0.58.4

There's not much else to go on as the build succeeds with no errors. Has anyone experienced a similar issue or have any ideas what might be the cause?

**Comment by andresrabinovich** [comment]
Having the same issue here. Could you find a way to fix it?

**Comment by andresrabinovich** [comment]
Managed to make it work in IOS. Installed it directly from git using npm install git+https://github.com/RobertSasak/react-native-openalpr/
Had to also add the framework AssetsLibrary.framework in xcode and finally used the example inside the folder Example (I put it in App.js as a test):

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  StatusBar,
  Button,
} from 'react-native';

import Camera from 'react-native-openalpr';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  textContainer: {
    position: 'absolute',
    top: 100,
    right: 50,
    bottom: 0,
  },
  text: {
    textAlign: 'center',
    fontSize: 20,
  },
  preview: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  overlay: {
    position: 'absolute',
    padding: 16,
    alignItems: 'center',
  },
  topOverlay: {
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0, 255, 0, 0.4)',
    alignItems: 'center',
  },
  bottomOverlay: {
    right: 0,
    left: 0,
    bottom: 0,
    backgroundColor: 'rgba(255,0,0,0.4)',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  }
});

export default class App extends React.Component {
  constructor(props) {
    super(props);

    this.camera = null;

    this.state = {
      camera: {
        aspect: Camera.constants.Aspect.fill,
      },
      plate: 'Scan a plate',
    };

  }


  onPlateRecognized = ({ plate, confidence }) => {
    if (confidence > 90) {
      this.setState({
        plate,
      })

    }
  }


  render() {
    return (
      <View style={styles.container}>
        <StatusBar
          animated
          hidden
        />
        <Camera
          ref={(cam) => {
            this.camera = cam;
          }}
          style={styles.preview}
          aspect={this.state.camera.aspect}
          captureQuality={Camera.constants.CaptureQuality.medium}
          country="us"
          onPlateRecognized={this.onPlateRecognized}
          plateOutlineColor="#ff0000"
          showPlateOutline
          torchMode={Camera.constants.TorchMode.off}
          touchToFocus
        />
        <View style={[styles.overlay, styles.topOverlay]}>
        </View>
        <View style={[styles.overlay, styles.bottomOverlay]}>
        </View>

        <View style={styles.textContainer}>
          <Text style={styles.text}>{this.state.plate}</Text>
        </View>
      </View>

    );
  }
}

**Comment by RobertSasak** [comment]
@andresrabinovich Do you mind to create a small PR regarding requiresMainQueueSetup ? I am sure it will take no more than few minutes.

**Comment by RobertSasak** [comment]
Closing this issue as master is published to NPM as 1.2.0.
