### ISSUE TITLE
Load then crashed on device

### ISSUE THREAD

**Issue by Lucienzera** [RobertSasak/react-native-openalpr#51]
App showed the camera for 1sec then crashes for both scenario:

1. Followed the instruction on README.md to test on the new project did not work.
2. Git cloned the example and follow the instruction on README.md still not working

Help please..

**Comment by RobertSasak** [comment]
What platform has it crashed?
Do you get any log messages in catlog or xcode?

**Comment by Lucienzera** [comment]
@RobertSasak on Android 9.0 where i set the sdk level to 28, same goes for openalpr and the opencv inside the node modules for react-native-openalpr

Im not sure about the log messages.

Thank you

**Comment by RobertSasak** [comment]
Closing in favour of https://github.com/RobertSasak/react-native-openalpr/releases/tag/v2.0.1
