### ISSUE TITLE
app crash on android after update to react-native 0.59

### ISSUE THREAD

**Issue by neil-zigit** [RobertSasak/react-native-openalpr#52]
i think it might related to the the new react-native 64-bit support.
does the libary going to support "arm64-v8a" architecture?

FATAL EXCEPTION: HandlerThread
 AndroidRuntime: Process: com.hertzserviceapp.dev, PID: 14591
 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.hertzserviceapp.dev-ZpOScjwz6yrN2-4EWzZWJA==/base.apk"],nativeLibraryDirectories=[/data/app/com.hertzserviceapp.dev-ZpOScjwz6yrN2-4EWzZWJA==/lib/arm64, /data/app/com.hertzserviceapp.dev-ZpOScjwz6yrN2-4EWzZWJA==/base.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "libopenalpr-native.so"
06-30 17:28:17.718 14591 14733 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
06-30 17:28:17.718 14591 14733 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1669)
06-30 17:28:17.718 14591 14733 E AndroidRuntime:        at org.openalpr.AlprJNIWrapper.<clinit>(AlprJNIWrapper.java:9)
06-30 17:28:17.718 14591 14733 E AndroidRuntime:        at org.openalpr.OpenALPR$Factory.create(OpenALPR.java:80)
06-30 17:28:17.718 14591 14733 E AndroidRuntime:        at com.cardash.openalpr.ALPR.executeRecognition(ALPR.java:119)
06-30 17:28:17.718 14591 14733 E AndroidRuntime:        at com.cardash.openalpr.ALPR.access$100(ALPR.java:35)
06-30 17:28:17.718 14591 14733 E AndroidRuntime:        at com.cardash.openalpr.ALPR$1.handleMessage(ALPR.java:55)
06-30 17:28:17.718 14591 14733 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
06-30 17:28:17.718 14591 14733 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
06-30 17:28:17.718 14591 14733 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by AguGriguol** [comment]
Hi!

Do you have openalpr libraries for x64 architectures (arm64, x86_x64, mips64)? Google needs to upload apks in 64 bits.
This is a great limitation, please we need the new libraries.

Thanks

**Comment by baleo-it** [comment]
Same problem here!

**Comment by belabed90** [comment]
Same i'm looking for 64 support

**Comment by RobertSasak** [comment]
I managed to update library to work with react 0.60. You can find changes in a separate branch. However I am struggling to find 64bit underlying libraries.

**Comment by RobertSasak** [comment]
Closing in favour of https://github.com/RobertSasak/react-native-openalpr/releases/tag/v2.0.1
