### ISSUE TITLE
Not able to run the package

### ISSUE THREAD

**Issue by shashank0495** [RobertSasak/react-native-openalpr#53]
I followed the steps given but not able to run the project , the error being shown is
import com.sandro.openalpr.CameraReactPackage;

but here sandro package does not exists?

**Comment by baleo-it** [comment]
same error here!

**Comment by baleo-it** [comment]
@shashank0495 replace your code with
```
// import com.sandro.openalpr.CameraReactPackage;
import com.cardash.openalpr.CameraReactPackage;
`
``

**Comment by shashank0495** [comment]
I tried replacing it with cardash but it used to get override with sandro
thing.

Shashank Tiwari

**Comment by baleo-it** [comment]
I guess the repo maintainer change has broke the package ids. Needs a PR to have com.sandro working.

**Comment by RobertSasak** [comment]
I am not sure what has to be done. Can you be please more specific?

**Comment by baleo-it** [comment]
@RobertSasak we got a "CameraReactPackage package cannot be found" error. It seems like replacing `import com.sandro.openalpr.CameraReactPackage;`with `import com.cardash.openalpr.CameraReactPackage;` makes it work. Do you know why?

But then I get another issue, I'll be reporting it ASAP. I'm working on it.

**Comment by belabed90** [comment]
I got the same error, how we solve this? 
i have replaced
 **import com.sandro.openalpr.CameraReactPackage;** with import **com.cardash.openalpr.CameraReactPackage;**
but the error stay exist

**Comment by belabed90** [comment]
@shashank0495  have you solved the problem?

**Comment by thongnvlb** [comment]
I had the same problem.

**Comment by RobertSasak** [comment]
I am looking into it right now, but I feel stuck. Join me on https://gitter.im/react-native-openalpr/community for brainstorming.

**Comment by RobertSasak** [comment]
Closing in favour of https://github.com/RobertSasak/react-native-openalpr/releases/tag/v2.0.1
