### ISSUE TITLE
pod install failed

### ISSUE THREAD

**Issue by WMaximusW** [RobertSasak/react-native-openalpr#55]
React native version 0.60.4

Fetching podspec for `RNOpenAlpr` from `../node_modules/react-native-openalpr/ios`
[!] The `RNOpenAlpr` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `homepage`.
    - WARN  | source: The version should be included in the Git tag.
    - WARN  | description: The description is equal to the summary.

**Comment by virgule-xyz** [comment]
Just open the RNOpenAlpr.podspec and fix the line 9 :
  s.homepage     = "https://github.com/RobertSasak/react-native-openalpr"
