### ISSUE TITLE
Is there a conflict with RNCamera

### ISSUE THREAD

**Issue by virgule-xyz** [RobertSasak/react-native-openalpr#57]
Hi,

1st, thanks for your job !

I'm facing a problem in my project, even after installing the whole plugin.

I use RN 0.60.4 and RN Camera 2.9.0.

The tag used is <Camera country="fr" onPlateRecognized={this.onRegistrationRead} />

No compile problem but after launch I've got "null is not an object (evaluating CameraManager.Aspect).

Can it be related to using RN Camera in the same project ?

**Comment by liyuchenf1** [comment]
Same here....
Have you solved it? I searched Google it looks like react-native link problem. But how can I link it properly?

**Comment by RobertSasak** [comment]
Try new 2.0.0 version which support RN 0.60. Closing for now.
