### ISSUE TITLE
Always crash on zoom

### ISSUE THREAD

**Issue by CevaComic** [RobertSasak/react-native-openalpr#64]
-[ALPRCamera handlePinchToZoomRecognizer:]: unrecognized selector sent to instance 0x15726aae0

On iOS, with classic example from this repo.

Any fix ?

**Comment by RobertSasak** [comment]
It seem like there was a plan for zoom that was never implemented. Can you try to remove line 56 and 57 from
https://github.com/RobertSasak/react-native-openalpr/blob/1ae6fe8eabdcc548aa1721704222f6498e7d8c2a/ios/ALPRCamera.m#L56

It would be perfect for super nice small PR.

**Comment by CevaComic** [comment]
for now i just added this to ALPRCamera.m

-(void) handlePinchToZoomRecognizer:(UIPinchGestureRecognizer*)pinchRecognizer {

    if (pinchRecognizer.state == UIGestureRecognizerStateChanged) {
        return;
    }
}

**Comment by RobertSasak** [comment]
What do you mean by selector? It looks good to me. Please make a small PR, so I can merge it and release update.

**Comment by CevaComic** [comment]
Ok. But this is just a temprary fix. Because zoom still won't work.

**Comment by RobertSasak** [comment]
This functionality has never been implemented as far I know.  I wonder why nobody spotted this issue before. Lets fix it first with your PR and then we can open new issue for implementing zoom.

**Comment by CevaComic** [comment]
This should help (for someone who knows swift)

https://github.com/react-native-community/react-native-camera/blob/master/ios/RCT/RCTCamera.m

**Comment by RobertSasak** [comment]
Fixed by https://github.com/RobertSasak/react-native-openalpr/pull/65 and published to NPM in https://github.com/RobertSasak/react-native-openalpr/releases/tag/v2.0.3
