### ISSUE TITLE
Xcode 'dyld: lazy symbol binding failed: can't resolve symbol ___cxa_guard_acquire in'

### ISSUE THREAD

**Issue by gfsd3v** [RobertSasak/react-native-openalpr#67]
Hello.

I have followed every step in the README and also tried to run the example app but I'm getting the following error when trying to run the app in XCode

`dyld: lazy symbol binding failed: can't resolve symbol ___cxa_guard_acquire in /Users/gabriel/Library/Developer/CoreSimulator/Devices/E2983EEC-BB6B-4F04-A5A6-350B11DCF58B/data/Containers/Bundle/Application/B51B68CC-6238-434D-865B-B45D56168053/RNOpenALPRExample.app/RNOpenALPRExample because dependent dylib #1 could not be loaded
dyld: can't resolve symbol ___cxa_guard_acquire in /Users/gabriel/Library/Developer/CoreSimulator/Devices/E2983EEC-BB6B-4F04-A5A6-350B11DCF58B/data/Containers/Bundle/Application/B51B68CC-6238-434D-865B-B45D56168053/RNOpenALPRExample.app/RNOpenALPRExample because dependent dylib #1 could not be loaded
(lldb)`

Anyone has any idea of what this could be related to or how to fix it ? Thanks in advance.

**Comment by RobertSasak** [comment]
Can it be related to https://stackoverflow.com/questions/52331634/xcode-10-0-gm-dyld-lazy-symbol-binding-failed-cant-resolve-symbol-cxa-gu ?
What version of simulator or device are you running it on?

**Comment by gfsd3v** [comment]
I saw this stackoverflow thread, Its a problem related to iOS 12 simulator. I ended up importing the OpenALPR framework directly in XCode. Thanks.
