### ISSUE TITLE
App Crashed

### ISSUE THREAD

**Issue by Lucienzera** [RobertSasak/react-native-openalpr#68]
Hey, I followed your setup and everything then upon opening the app crashed straight away

**Comment by RobertSasak** [comment]
Can you please run the example folder first? If it crash, can you please provide some error message?

**Comment by marcelocferdeveloper** [comment]
I am with the same problem... 
But I am a begginer with Android Studio. It´s not appearing where is the error... just crash the app and close it.

**Comment by im-amir** [comment]
My client's app crashed too when I sent him release apk of the example provided in Github because he was using Android 9. But the same generated apk did not crash on mine QMobile. I think it's due to some Android 9 compatibility issue

**Comment by RobertSasak** [comment]
Android is not really supported, we are missing 64bit libraries.
