### ISSUE TITLE
camera deprecated because of camera2 api

### ISSUE THREAD

**Issue by marcelocferdeveloper** [RobertSasak/react-native-openalpr#69]
I am new on React and I am trying to run this project. I did step by step, but I got this error when trying in some new phone models (physical):

openalpr\ALPRCameraView.java: uses or overrides a deprecated API.
Recompile with -Xlint:deprecation for details.
Some input files use unchecked or unsafe operations.
Recompile with -Xlint:unchecked for details.

Thanks

**Comment by RobertSasak** [comment]
FYI: https://github.com/RobertSasak/react-native-openalpr/issues/61

**Comment by marcelocferdeveloper** [comment]
Which device, for example, the app works now ?

**Comment by RobertSasak** [comment]
iOS. It works on Android, but you cannot publish non 64bit on Google Play any more.

**Comment by marcelocferdeveloper** [comment]
Ok !! No, it´s just to try for now...

**Comment by RobertSasak** [comment]
Strange that toFixed does not exists. Perhaps it is older JS engine.
