### ISSUE TITLE
Can not detect vietnamese 2 line plates

### ISSUE THREAD

**Issue by vinpro24** [RobertSasak/react-native-openalpr#72]
I have issue with vn2
US & EU plates working fine but not working Vietnamese 2 line plates
Any idea? Thank you

**Comment by RobertSasak** [comment]
You may need to edit config file at `runtime_data/openalpr.conf`
Quick search revealed this file.
https://github.com/openalpr/openalpr/blob/master/runtime_data/config/vn2.conf

**Comment by vinpro24** [comment]
How to edit config at runtime_data/openalpr.conf?
Add vn2.conf below final line openalpr.conf?

**Comment by RobertSasak** [comment]
I think you just replace the content of the whole file.

**Comment by vinpro24** [comment]
I replace the content of file but still not work.

**Comment by vinpro24** [comment]
> I think you just replace the content of the whole file.

any idea? please

**Comment by RobertSasak** [comment]
You need to read more about OpenAlpr at their homepage. Try to come up with more specific problem description. What does not exactly work? What plates? Screenshots? Two rows? Color?

**Comment by KevinZhanggg** [comment]
@vinpro24 Did you solve it ?

**Comment by vinpro24** [comment]
> @vinpro24 Did you solve it ?

Not yet
