### ISSUE TITLE
it seems that you device dows not support camera (or it is locked).

### ISSUE THREAD

**Issue by reacthukuk** [RobertSasak/react-native-openalpr#74]
I added codes preview class which is at the below  
---------------------   
```js
preview: {
        flex: 1,
    }
```
or
```js
    preview: {
        width: 600,
        height: 400,
    }
```
----------------------
I took this error message : it seems that you device dows not support camera (or it is locked). Application will be closed. 
I gived a permission to camera.
How can I fixed this problem?
If you help me I will be pleasure.

**Comment by RobertSasak** [comment]
Are you testing on real device or simulator? Sounds like simulator.
iOS or Android?

**Comment by reacthukuk** [comment]
I tested on twice real and simulator on Android.

my app.js
------
import React, { Component } from 'react'
import { StyleSheet, Text, View, PermissionsAndroid } from 'react-native'

import Camera, {
    Aspect,
    CaptureQuality,
    TorchMode,
} from 'react-native-openalpr'

async function requestCameraPermission() {
    try {
        const granted = await PermissionsAndroid.request(
            PermissionsAndroid.PERMISSIONS.CAMERA,
            {
                title: 'Cool Photo App Camera Permission',
                message:
                    'Cool Photo App needs access to your camera ' +
                    'so you can take awesome pictures.',
                buttonNeutral: 'Ask Me Later',
                buttonNegative: 'Cancel',
                buttonPositive: 'OK',
            },
        );
        if (granted === PermissionsAndroid.RESULTS.GRANTED) {
            console.log('You can use the camera');
        } else {
            console.log('Camera permission denied');
        }
    } catch (err) {
        console.warn(err);
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    preview: {
        flex: 1,
    },
    prex: {
        flex: 1,
        backgroundColor: "#336699"
    },
    textContainer: {
        position: 'absolute',
        top: 100,
        left: 50,
    },
    text: {
        textAlign: 'center',
        fontSize: 20,
    },
})

export default class PlateRecognizer extends React.Component {
    async componentDidMount() {
        await requestCameraPermission()
    }


    state = {
        plate: 'Scan a plateaaaaa!1',
    }

    onPlateRecognized = ({ plate, confidence }) => {
        this.setState({
            plate,
        })
    }

    render() {
        return (
            <View style={styles.container}>
                <View style={styles.prex}>
                    <Text>sadkjksadjlklasdjkljskad</Text>
                </View>
                <Camera
                    style={styles.preview}
                    aspect={Aspect.fill}
                    captureQuality={CaptureQuality.medium}
                    country="eu"
                    onPlateRecognized={this.onPlateRecognized}
                    plateOutlineColor="#ff0000"
                    showPlateOutline
                    torchMode={TorchMode.off}
                    touchToFocus
                />
                <View style={styles.textContainer}>
                    <Text style={styles.text}>{this.state.plate}</Text>
                </View>
            </View>
        )
    }
}

**Comment by RobertSasak** [comment]
Can you please try the example folder from this repo?
I am not sure what exactly is the issue. Can you please describe it in more detail?

**Comment by ederwan** [comment]
Hi, try to go in the setting -> yourapp -> permission -> enable camera
