### ISSUE TITLE
Execution failed for task ':opencv:compileDebugAidl'.

### ISSUE THREAD

**Issue by busraguler** [RobertSasak/react-native-openalpr#76]
* What went wrong:
Execution failed for task ':opencv:compileDebugAidl'.
> Could not read path 'C:\reactnative\ggg\node_modules\react-native-openalpr\android\libraries\opencv\build\generated\a�dl_source_output_d�r\debug\compileDebugAidl\out\org\opencv'.

**Comment by busraguler** [comment]
why don't you answer here?

**Comment by RobertSasak** [comment]
Sounds like the versions of SDK, Build Tools and Gradle Plugins doesn't match.
https://stackoverflow.com/questions/29766830/execution-failed-for-task-appcompiledebugaidl-aidl-is-missing
