### ISSUE TITLE
Using Example App.js, app crashes after a few seconds: Java and OpenCV error: cannot Cannot load info library for OpenCV

### ISSUE THREAD

**Issue by datafaust** [RobertSasak/react-native-openalpr#77]
I have installed the package and followed the documentation, altering files as directed. I have added the example/App.js file to run. I am on Ubuntu 18. I run react-native start, the app renders in both emulator and pixel2 physical device, but crashes after a few seconds without pressing anything.

I am see the following errors in android studio and was hoping you might be able to point me in the right direction since I notice there seem to be some recent issues popping up, thank you:

ERROR 1 
...
D/CameraBridge: call checkCurrentState
D/OpenCV/StaticHelper: Trying to get library list
**_E/OpenCV/StaticHelper: OpenCV error: Cannot load info library for OpenCV_**
D/OpenCV/StaticHelper: Library list: ""
    First attempt to load libs
    Trying to init OpenCV libs
    Trying to load library opencv_java3
D/OpenCV/StaticHelper: Library opencv_java3 loaded
    First attempt to load libs is OK

And then towards the end of the run:
ERROR 2:
D/JavaCameraView: startPreview
D/JavaCameraView: Starting processing thread
I/Choreographer: Skipped 57 frames!  The application may be doing too much work on its main thread.
I/ALPR: handleMessage
    executeRecognition
**_E/AndroidRuntime: FATAL EXCEPTION: HandlerThread
    Process: com.license, PID: 14546
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.license-Md7LtJvOjK2CwJPjQ-bKZQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.license-Md7LtJvOjK2CwJPjQ-bKZQ==/lib/x86, /data/app/com.license-Md7LtJvOjK2CwJPjQ-bKZQ==/base.apk!/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libopenalpr-native.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at org.openalpr.AlprJNIWrapper.<clinit>(AlprJNIWrapper.java:9)
        at org.openalpr.OpenALPR$Factory.create(OpenALPR.java:80)
        at com.cardash.openalpr.ALPR.executeRecognition(ALPR.java:119)
        at com.cardash.openalpr.ALPR.access$100(ALPR.java:35)
        at com.cardash.openalpr.ALPR$1.handleMessage(ALPR.java:55)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)_**
D/ReactContextBaseJavaModule: onHostPause
D/ReactContextBaseJavaModule: receiver already unregistered
D/CameraBridge: call checkCurrentState
    call processExitState: 1
D/JavaCameraView: Disconnecting from camera
    Notify thread
    Wating for thread
D/eglCodecCommon: allocate: Ask for block of size 0x391000
D/eglCodecCommon: allocate: ioctl allocate returned offset 0x3ff406000 size 0x392000
D/JavaCameraView: Finish processing thread
D/CameraBridge: call processEnterState: 0
I/Choreographer: Skipped 31 frames!  The application may be doing too much work on its main thread.
D/CameraBridge: call checkCurrentState
D/EGL_emulation: eglMakeCurrent: 0xe2637700: ver 2 0 (tinfo 0xe2666e00)
D/ReactNative: ReactInstanceManager.detachViewFromInstance()
D/ReactContextBaseJavaModule: onHostDestroy
    receiver already unregistered
D/CameraBridge: call checkCurrentState
Process 14546 terminated.

**_My package.json_**
{
  "name": "license",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "postinstall": "npx jetify"
  },
  "dependencies": {
    "jsc-android": "^245459.0.0",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-openalpr": "^2.0.3",
    "react-native-permissions": "^2.0.8"
  },
  "devDependencies": {
    "@babel/core": "7.7.7",
    "@babel/runtime": "7.7.7",
    "@react-native-community/eslint-config": "0.0.5",
    "babel-jest": "24.9.0",
    "eslint": "6.8.0",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.56.3",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by RobertSasak** [comment]
There are not 64bit sub libraries for Android. 
https://github.com/RobertSasak/react-native-openalpr/issues/61
