### ISSUE TITLE
Can we also get support for Turkey?

### ISSUE THREAD

**Issue by busraguler** [RobertSasak/react-native-openalpr#78]
Can we also get support for Turkey?
![il-plaka-kodları](https://user-images.githubusercontent.com/16039532/71472493-50368b00-27e4-11ea-851c-2c1f8c550d09.jpg)

**Comment by RobertSasak** [comment]
You need to get config for Turkey. This repo is just a wrapper around OpenAlpr.  
https://github.com/RobertSasak/react-native-openalpr/issues/72#issuecomment-566448673
