### ISSUE TITLE
I was able to get build, but when the camera is turned on, the app is locked !!!

### ISSUE THREAD

**Issue by busraguler** [RobertSasak/react-native-openalpr#79]
I was able to get build, but when the camera is turned on, the app is locked !!! 
Please help me.

**Comment by RobertSasak** [comment]
What does it mean that the app is locked?
What platform are you running on?

**Comment by busraguler** [comment]
When I run the application, it closes after 1 to 2 seconds (Window, Android. )

**Comment by busraguler** [comment]
I think this error was caused by the camera.

**Comment by RobertSasak** [comment]
Android platform is currently not supported as there are no 64bit openAlpr libraries. There is open issue about this. 
https://github.com/RobertSasak/react-native-openalpr/issues/61
