### ISSUE TITLE
Not able to run on android even 32 bit version

### ISSUE THREAD

**Issue by kamellababidi** [RobertSasak/react-native-openalpr#81]
built with the following error:

/Users/kamel/Desktop/repo-coin-scanner/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:34: error: cannot find symbol
import com.sandro.openalpr.CameraReactPackage;
                          ^
  symbol:   class CameraReactPackage
  location: package com.sandro.openalpr
/Users/kamel/Desktop/repo-coin-scanner/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:96: error: cannot find symbol
      new CameraReactPackage(),
          ^
  symbol:   class CameraReactPackage
  location: class PackageList
2 errors

**Comment by RobertSasak** [comment]
What version of react native are you using?

**Comment by kamellababidi** [comment]
@RobertSasak 
I'm using the following versions
    "react": "16.9.0",
    "react-native": "0.61.1",

**Comment by RobertSasak** [comment]
Are you running example forlder? If not can you try it first?

**Comment by kamellababidi** [comment]
it tried and now I'm getting this error:


Could not resolve all dependencies for configuration ':app:_debugApk'.
A problem occurred configuring project ':react-native-openalpr'.
Could not resolve all dependencies for configuration ':react-native-openalpr:_debugPublish'.
Configuration with name 'default' not found.

**Comment by kamellababidi** [comment]
I tried and now I'm getting the following error :
Could not resolve all dependencies for configuration ':app:_debugApk'.
A problem occurred configuring project ':react-native-openalpr'.
Could not resolve all dependencies for configuration
':react-native-openalpr:_debugPublish'.
Configuration with name 'default' not found.

**Comment by kamellababidi** [comment]
I figured out the issue
there was a problem in settings.gradle file
