### ISSUE TITLE
Crash when authorising the camera on android 

### ISSUE THREAD

**Issue by ederwan** [RobertSasak/react-native-openalpr#86]
Hi, I was unable to make it work on android (i follow the tuto to use the exemple), every time i accept the camera authorisation, it crash. I was unable to have log about it. I saw problem about android 64 bit on other issues but i was unable to understand if it's over or not. Do you have recommendation to make it work on android ? Thank you

**Comment by RobertSasak** [comment]
64bit is not resolved yet. It is not possible to publish app into Google Play. However I am able to run example on my Android phone. 

I just published version 2.1.1 which fixed small issue with toFixed. I think that may be the issue that you encountered.

**Comment by ederwan** [comment]
I upgrade the package with yarn but it crash again after authorising the camera...
I don't understand how it's possible because i only use the exemple.

**Comment by RobertSasak** [comment]
It is clearly the issue with 64bit libraries. Your phone cannot find it, because they do not exists.

**Comment by ederwan** [comment]
But i dont understand how  to run 32bits app, my 64 bits phone should be able to run it.

**Comment by ederwan** [comment]
Ok, it work, it was my mistack, i was unable to create a 32 bit apk. To do so I add        
```
 ndk {
            abiFilters "armeabi", "armeabi-v7a", "x86", "mips"
        }
```
In build.gradle(:app) -> 
`android {
    ....
    defaultConfig {
        ....
        ndk {
            abiFilters "armeabi", "armeabi-v7a", "x86", "mips"
        }
    }
}`
