### ISSUE TITLE
Plugin does not work

### ISSUE THREAD

**Issue by maiconcosta** [RobertSasak/react-native-openalpr#87]
Is there a problem with the repository?
I installed it in my application, and used the sample code, when pointing to a plate, the outline did not appear and the plate was not read.

I'm using android.

I tried to read the plates for Brazil, the United States and Europe.

**Comment by RobertSasak** [comment]
Hard to tell where can be an issue. Example for works for me and recognise EU plates.

**Comment by maiconcosta** [comment]
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/20714075/76428883-08f47b00-638d-11ea-998c-56c5f57621de.gif)

**Comment by RobertSasak** [comment]
Have you try to run an example folder alone? It is hard to debug your custom project.

**Comment by maiconcosta** [comment]
Sorry, I did a test just with the example directory and it worked. I will adapt it to my project, thank you!
