### ISSUE TITLE
Crash on Country MX

### ISSUE THREAD

**Issue by betocantu93** [RobertSasak/react-native-openalpr#9]
Hello, thanks for this lib, great job! 

When compiling my react native project using country="mx", the camera don't work, literally if I change to 'us' it works, rarely enough if I use the live reload tool and change it to 'mx' (compiled in 'us') it works as expected.

So the issue, unable to compile using another country than 'us'.

And it breaks in this line of code on xcode project.

![screen shot 2017-05-17 at 2 34 50 am](https://cloud.githubusercontent.com/assets/9092644/26143175/7597364a-3aa9-11e7-8708-a0da455e9a94.png)

Thanks in advance

**Comment by andresrabinovich** [comment]
Having the same issue with au and eu, any ideas?

**Comment by RobertSasak** [comment]
I just clone the repo. Open Example folder and iOS folder in XCode. Change country to eu and then to au. I cannot reproduce your issue. Both au and eu works. 
Can you please provide info how to reproduce this issue?

**Comment by maryaibtissem** [comment]
Having the same issue

**Comment by RobertSasak** [comment]
@maryaibtissem Can you please provide more information?

**Comment by maryaibtissem** [comment]
hi, the application crash when i change country to 'eu', but country = 'us' works fine
<img width="752" alt="Capture d’écran 2020-05-26 à 14 20 40" src="https://user-images.githubusercontent.com/23694894/82900024-297bac80-9f5c-11ea-9278-70e83bf7e1c0.png">
