### ISSUE TITLE
Hello, do you support license plate recognition in Singapore?

### ISSUE THREAD

**Issue by Dreamskya** [RobertSasak/react-native-openalpr#90]

**Comment by RobertSasak** [comment]
This library is just a wrapper around OpenAlpr. It will recognise plates of the country specified in config file. If there is a a config file for your country you need to search at https://github.com/openalpr/openalpr

**Comment by Dreamskya** [comment]
thank you

**Comment by Dreamskya** [comment]
country
Specifies which OpenALPR config file to load, corresponding to the country whose plates you wish to recognize. Currently supported values are:

    au
    br
    eu
    fr
    gb
    kr
    mx
    sg
    us
    vn2
Hello, I see your document about supporting Singapore (SG). It seems that I can't use it. I can't support the license plate of this country. The identification interface is filled with "SG". I don't know why? Is it not supported, or am I using the wrong method?

**Comment by RobertSasak** [comment]
The way I understand it is following. OpenAlpr train their model on on different country licence plate. As a result they got different models/parameters. Those are specified in 
https://github.com/RobertSasak/react-native-openalpr/blob/master/example/android/app/src/main/assets/runtime_data/openalpr.conf

I guess if you would add a new section into this file *SG* you could change country to SG and recognise SG plates.

**Comment by Dreamskya** [comment]
I see. Do you have the model parameters of Singapore? Is it the parameter used in openalpr.conf? I'm an Android Developer and I don't understand algorithms. Or do you have a demo that can run license plate recognition in Singapore?
  protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        if(resultCode == RESULT_OK) {

            String openAlprConfFile = ANDROID_DATA_DIR + File.separatorChar +
                    RUNTIME_DATA_DIR_ASSET + File.separatorChar +OPENALPR_CONF_FILE;
            handleBigCameraPhoto();
            String parameters[] = {/*"ca"*//*"us"*/"SG", "", this.mCurrentPhotoPath, openAlprConfFile, "1"};
            Bundle args = new Bundle();
            args.putStringArray(ALPR_ARGS, parameters);
            AlprFragment alprFragment = (AlprFragment)getFragmentManager()
                    .findFragmentByTag(ALPR_FRAGMENT_TAG);

            if(alprFragment == null){
                alprFragment = new AlprFragment();
                alprFragment.setArguments(args);

                FragmentTransaction transaction = getFragmentManager().beginTransaction();
                transaction.add(alprFragment, ALPR_FRAGMENT_TAG);
                transaction.commitAllowingStateLoss();
            }
        }
    }
I have tried to give "SG"  national parameters, and found that they can't

**Comment by RobertSasak** [comment]
I am not sure what above code means. I think you want to start with standalone OpenAlpr make it work with SG plates. And then try this wrapper.

Yes, you need to add section SG into openalpr.conf

**Comment by Dreamskya** [comment]
thank you



zhangtao@simtoo.com
 
From: Robert Sasak
Date: 2020-04-14 16:29
To: RobertSasak/react-native-openalpr
CC: Dreamskya; Author
Subject: Re: [RobertSasak/react-native-openalpr] Hello, do you support license plate recognition in Singapore? (#90)
I am not sure what above code means. I think you want to start with standalone OpenAlpr make it work with SG plates. And then try this wrapper.
Yes, you need to add section SG into openalpr.conf
