### ISSUE TITLE
Disable plate rectangle after recognition

### ISSUE THREAD

**Issue by makkimadani** [RobertSasak/react-native-openalpr#91]
how can I disable plate rectangle after recognition finished? and how to start / stop recognition ?

**Comment by RobertSasak** [comment]
Recognition is always on. You may ignore the recognitions that you do not need. 
You can hide rectangle with _showPlateOutline_.

**Comment by makkimadani** [comment]
i need to show the plateOutLine and disable it after detection.. is there any way ?

**Comment by RobertSasak** [comment]
No this is not possible.
