### ISSUE TITLE
OpenAlpr not working on android in release mode

### ISSUE THREAD

**Issue by harrischelsea** [RobertSasak/react-native-openalpr#92]
I have a problem with library in release mode on android.
It works fine on IOS (debug/release) and ANDROID debug.

It shows camera but it not recognize anything at all.

Can anyone help with this?

**Comment by RobertSasak** [comment]
There are no 64bit libs for Android. Could that b a problem?
https://github.com/RobertSasak/react-native-openalpr/issues/61

**Comment by harrischelsea** [comment]
Robert, thank you for sour answer. Mayve that could be a problem. Is there any solution for this? Does anyone have this problem?

**Comment by RobertSasak** [comment]
This library is just a wrapper around non existing native app.  Somebody need to create those 64bit libraries. There is no other way.

**Comment by kaangultekin** [comment]
Hi, Anybody have a solution?

**Comment by RobertSasak** [comment]
@kaangultekin This library does not support Android in release mode. There is no solution at the moment nor nobody is actively working on it.

**Comment by kaangultekin** [comment]
so does it mean that openalpr is not available for Android? I could
not understand.


6 Oca 2021 Çar 18:34 tarihinde Robert Sasak <notifications@github.com> şunu
yazdı:

**Comment by RobertSasak** [comment]
You cannot publish app to Google Play Store which is not using 64bit libraries. So any app containing this library cannot be published into store. https://github.com/RobertSasak/react-native-openalpr/issues/61

You can still test it on your phone if you want in debug mode. Again I suggest that you start with making it work on example folder on your phone before your try to drop this library into your existing app.

**Comment by kaangultekin** [comment]
Thank you Robert. I will try. you are awesome.

6 Oca 2021 Çar 18:47 tarihinde Robert Sasak <notifications@github.com> şunu
yazdı:

**Comment by unwmun** [comment]
If it is just a problem that does not run in release mode on android, you should check the ProGuard settings. 
if your build.gradle(app) settings:
```
android {
...
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }
...
}
```
Add the ProGuard rule that can be resolved the problem:

**app/proguard-rules.pro**
```
...
# Open ALPR
-keep class org.openalpr.** { *; }
```

**Comment by kamellababidi** [comment]
@unwmun 
Have you tried that solution and working fine for you?!  
If so, please let us know as we all waiting for a solution on android.

Thanks!
