### ISSUE TITLE
react-native android app crash 

### ISSUE THREAD

**Issue by aniruddhbhamare** [RobertSasak/react-native-openalpr#93]
"react": "16.9.0",
"react-native": "0.61.5",
 "react-native-openalpr": "^2.1.1",
"react-native-permissions": "^2.0.9",

camera open n after 2 - 3 sec. app crashes on android

**Comment by RobertSasak** [comment]
Duplicate of this https://github.com/RobertSasak/react-native-openalpr/issues/61 ?

**Comment by waheedshabeer** [comment]
please give solution

**Comment by RobertSasak** [comment]
Without further information there is nothing to be done.

**Comment by duartejc** [comment]
I fixed similar crash issue adding this configuration in _app/build.gradle_ file:

```
android {
    ...
    defaultConfig {
       ...
        ndk { 
            abiFilters "armeabi-v7a" 
        } 
    }
}
```
