### ISSUE TITLE
Generated duplicate UUIDs

### ISSUE THREAD

**Issue by juniortrials** [RobertSasak/react-native-openalpr#94]
hello all good, first congratulations on the work with the library I believe it helps many projects, I am trying to install the library on IOS RN 0.6.2 to run on the iphone, and it presents this after the pod install,
[!] Can't merge user_target_xcconfig for pod targets: ["MobileVLCKit", "TesseractOCRiOS"]. Singular build setting CLANG_CXX_LIBRARY has different values.

[!] Can't merge user_target_xcconfig for pod targets: ["MobileVLCKit", "TesseractOCRiOS"]. Singular build setting CLANG_CXX_LIBRARY has different values.

[!] Can't merge user_target_xcconfig for pod targets: ["MobileVLCKit", "TesseractOCRiOS"]. Singular build setting CLANG_CXX_LIBRARY has different values.

[!] Can't merge user_target_xcconfig for pod targets: ["MobileVLCKit", "TesseractOCRiOS"]. Singular build setting CLANG_CXX_LIBRARY has different values.

[!] [Xcodeproj] Generated duplicate UUIDs:

lib MobileVLCKit I already use for RTSP video player,

thank you

**Comment by RobertSasak** [comment]
It seems that you are using MobileVLCKit, I am not really sure what is it for. I suggest that you start with *example* folder and gradually add more libraries one by one.

**Comment by juniortrials** [comment]
tks
