### ISSUE TITLE
No camera after following setup instructions.

### ISSUE THREAD

**Issue by richiepreece** [RobertSasak/react-native-openalpr#95]
Hi!

I have followed the setup instructions for Android but I'm struggling to get it to work.

![image](https://user-images.githubusercontent.com/1470437/87344602-0016e000-c50c-11ea-801f-13a4bc940ab9.png)

I have a project that is very simply using the example provided in the README.md file, but this is all I see. The setup instructions seem fairly straightforward, but I'm a little confused by this section:

![image](https://user-images.githubusercontent.com/1470437/87344624-06a55780-c50c-11ea-8a15-62d51d03ea82.png)

I coped over the openalpr.config file from the example project, changed my runtime_dir to `runtime_dir = /data/data/com.platesnative/runtime_data` rebuilt the project and the above screenshot is the result.

Is that not the correct way to set this up? Is there something else I should be doing?

**Comment by richiepreece** [comment]
As a follow up thought, the readme says `copy and paste the directory with the runtime needed data to your project at path`. That line is super confusing. I'm not sure what files I should be copying and where they should be copied to. The only one I coped was the `openalpr.conf` file, but it obviously was inadequate for the setup.

**Comment by RobertSasak** [comment]
I suggest to start with the example folder. Make it run first. Once done, you can try with your own repo and custom paths. openalpr.conf is usually in assets folder.

Android is however missing 64bit libs and you won't be able to run on some of the devices and won't be able to submit it to Play Store. See the pined issue.
